name: Build and Push the Docker Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set GIT_TAG env variable
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}"

      - name: Build image
        run: docker build . -t ${{ secrets.DOCKER_USER }}/rq-exporter:latest -t ${{ secrets.DOCKER_USER }}/rq-exporter:${GIT_TAG}

      - name: Run the tests
        run: docker run --rm --entrypoint python ${{ secrets.DOCKER_USER }}/rq-exporter:latest -m unittest

      - name: Push image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USER }}/rq-exporter:latest
          docker push ${{ secrets.DOCKER_USER }}/rq-exporter:${GIT_TAG}
